Repository saurabh-dev-vns/car-rental, pull requests merged in 2025-01, with the labels that each got.

#63 Added learn more page
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Pages/LearnMore.css
  client/src/Pages/LearnMore.jsx
  client/src/components/Hero/Hero.jsx
Labels: SWOC, Intermediate, Completed ✅

#87 added faq section
  client/src/Pages/Home.jsx
  client/src/components/FAQ/FAQ.css
  client/src/components/FAQ/FAQ.jsx
Labels: SWOC, Beginner, Completed ✅

#89 fixed space and wrapped text
  client/src/components/Working/Work.css
  client/src/components/Working/Work.jsx
Labels: SWOC, Beginner, Completed ✅

#94 updated 'about us' UI
  client/src/Pages/about.css
  client/src/components/Card/Card.css
Labels: good first issue, SWOC, Beginner, Completed ✅
